# Generated by Django 5.1.4 on 2025-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Образ жизни', 'Образ жизни'), ('tech', 'Технологии'), ('science', 'Наука'), ('fashion', 'Мода'), ('food', 'Еда')], max_length=100),
        ),
    ]
