# Generated by Django 5.1.4 on 2025-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии'), ('science', 'Наука'), ('fashion', 'Мода'), ('food', 'Еда'), ('lifestyle', 'Образ жизни')], max_length=100),
        ),
    ]
